# Generated by Django 5.0.3 on 2024-03-07 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.IntegerField(verbose_name='Номер')),
                ('capacity', models.IntegerField(verbose_name='Місткість')),
                ('description', models.TextField(verbose_name='Опис')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('image', models.ImageField(null=True, upload_to='rooms', verbose_name='Зображення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookingapp.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номери',
                'ordering': ['numbers'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(verbose_name='Дата заїзду')),
                ('check_out', models.DateTimeField(verbose_name='Дата виїзду')),
                ('phone', models.CharField(max_length=14)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клієнт')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingapp.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['creation_time'],
            },
        ),
    ]
